sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - master # build master branch only
script:
  - npm install
  - hexo generate # generate static files
deploy:
  provider: gcs
  access_key_id: "GOOGWIIXYJFTPM7BMYSP7N7H"
  secret_access_key: "GXAH7oyNkgdcMgNFaxGQUpAfK75t8VqeCwZlfDQe"
  bucket: "nayan-blogs"
  skip_cleanup: true
  acl: public-read
