sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - master # build master branch only
script:
  - git clone https://github.com/ppoffice/hexo-theme-hueman.git themes/hueman
  - npm install -S hexo-generator-json-content
  - cd themes/hueman
  - mv _config.yml.example _config.yml 
  - cd ..
  - cd ..
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: public