name: Deploy to GitHub pages
on:
  push:
    branches:
      - master
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: |
          npm install
          
      - name: Install Hexo CLI
        run: sudo npm install -g hexo-cli
      
      - name: Generate static website
        run: hexo generate

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: blog
